export const skills = [
    'UX Development',
    'CCP(AWS)',
    'React.js',
    'TypeScript',
    'Javascript',
    'jQuery',
    'CSS3',
    'SCSS',
    'Styled Components',
    'Cypress.io',
    'UX Design',
    'Visual Design',
    'Sketch',
    'Balsamiq',
    'Adobe Creative Suite',
    'Accessibility',
    'AxeCore',
    'pa11y',
];
